import {useEffect,useMemo,useRef,useState} from 'react';
import {Background,Controls,Edge,Handle,Node,Position,ReactFlow} from '@xyflow/react';
import Plot from 'react-plotly.js'; import {InlineMath} from 'react-katex';

type Event={task_id:string;sequence:number;timestamp:string;event_type:string;node?:string;title:string;summary:string;payload:Record<string,unknown>;duration_ms?:number};
type Task={task_id:string;user_query:string;status:string;plan:any[];tool_calls:any[];model_calls:any[];model_provider:string;verification_results:any[];artifacts:any[];final_answer?:string;retry_count:number;parsed_problem:any};
type Example={id:string;title:string;query:string;expected_tool:string;method:string;verification:string;discussion:string};
const nodeNames=['understand_problem','plan_solution','human_review','execute_tools','verify_result','render_visualization','explain_result','finalize'];
const labels:Record<string,string>={understand_problem:'理解问题',plan_solution:'制定方案',human_review:'人工审核',execute_tools:'执行工具',verify_result:'验证结果',render_visualization:'生成图表',explain_result:'教学解释',finalize:'汇总完成'};
const positions=[[0,30],[210,30],[420,30],[630,30],[630,180],[420,180],[210,180],[0,180]];
function FlowNode({data}:{data:any}){return <div className={`flow-node ${data.state}`}><Handle type="target" position={Position.Left}/><span>{data.label}</span>{data.detail&&<small>{data.detail}</small>}<Handle type="source" position={Position.Right}/></div>}
const nodeTypes={lesson:FlowNode};
function App(){
 const [examples,setExamples]=useState<Example[]>([]),[query,setQuery]=useState('使用 Newton 法求解 cos(x) - x = 0，初值 0.5，并显示迭代和残差');
 const [task,setTask]=useState<Task|null>(null),[events,setEvents]=useState<Event[]>([]),[teaching,setTeaching]=useState(false),[useModel,setUseModel]=useState(true),[modelStatus,setModelStatus]=useState<any>(null),[tol,setTol]=useState(1e-8),[retries,setRetries]=useState(2),[selected,setSelected]=useState<Event|null>(null),[busy,setBusy]=useState(false);
 const source=useRef<EventSource|null>(null);
 useEffect(()=>{if(!task?.task_id)return;const id=task.task_id;const timer=setInterval(()=>loadState(id),1500);return()=>clearInterval(timer)},[task?.task_id]);
 useEffect(()=>{fetch('/api/examples').then(r=>r.json()).then(setExamples);fetch('/api/model/status').then(r=>r.json()).then(setModelStatus); const id=localStorage.getItem('scidemo-task'); if(id) load(id)},[]);
 function load(id:string){fetch(`/api/tasks/${id}`).then(r=>{if(!r.ok)throw 0;return r.json()}).then(d=>{setTask(d.task);setEvents(d.events); if(!['completed','failed'].includes(d.task.status)) listen(id)}).catch(()=>localStorage.removeItem('scidemo-task'))}
 function listen(id:string){source.current?.close();const es=new EventSource(`/api/tasks/${id}/events`);source.current=es;es.onmessage=e=>{const item=JSON.parse(e.data);setEvents(old=>old.some(x=>x.sequence===item.sequence)?old:[...old,item]);loadState(id);if(['workflow_completed','workflow_failed'].includes(item.event_type))es.close()}}
 function loadState(id:string){fetch(`/api/tasks/${id}`).then(r=>r.json()).then(d=>{setTask(d.task);setBusy(!['completed','failed','waiting_review','rejected'].includes(d.task.status))})}
 async function run(){setBusy(true);setEvents([]);setTask(null);const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,teaching_mode:teaching,use_local_model:useModel,tolerance:tol,max_retries:retries})});const d=await r.json();localStorage.setItem('scidemo-task',d.task_id);listen(d.task_id);loadState(d.task_id)}
 async function review(action:string){if(!task)return;setBusy(true);await fetch(`/api/tasks/${task.task_id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,parameters:{tolerance:tol}})});listen(task.task_id);setTimeout(()=>loadState(task.task_id),100)}
 const nodes:Node[]=useMemo(()=>nodeNames.map((id,i)=>{const related=events.filter(e=>e.node===id);let state='idle';if(related.some(e=>e.event_type==='node_started'))state='running';if(related.some(e=>e.event_type==='node_completed'))state='done';if(related.some(e=>e.event_type==='human_review_required')&&task?.status==='waiting_review')state='review';if(related.some(e=>e.event_type==='tool_failed')||(id==='verify_result'&&related.some(e=>e.event_type==='verification_completed'&&(e.payload as any).passed===false)))state='failed';return{id,type:'lesson',position:{x:positions[i][0],y:positions[i][1]},data:{label:labels[id],state,detail:state==='review'?'等待批准':state==='running'?'运行中':state==='done'?'已完成':''}}}),[events,task?.status]);
 const edges:Edge[]=useMemo(()=>{const base:Edge[]=nodeNames.slice(0,-1).map((id,i)=>({id:`${id}-${nodeNames[i+1]}`,source:id,target:nodeNames[i+1],animated:nodes[i].data.state==='running'}));if(events.some(e=>e.event_type==='retry_started'))base.push({id:'retry',source:'verify_result',target:'execute_tools',animated:true,label:`重试 ${task?.retry_count||1}`,style:{stroke:'#f97316'}});return base},[nodes,events,task?.retry_count]);
 return <main><header><div><h1>SciDemo <span>科学计算 Agent 教学台</span></h1><p>本地模型做理解、工具选择与解释 · 科学库做计算 · 程序做验证</p></div><div className="head-status"><span className={`model-dot ${modelStatus?.available?'online':'offline'}`}/>{modelStatus?.available?`${modelStatus.provider} 在线`:'本地模型离线'}<div className={`status ${task?.status||'ready'}`}>{task?.status||'ready'}</div></div></header>
 <section className="grid"><aside className="panel controls"><h2>问题与控制</h2><label>课堂示例<select onChange={e=>{const x=examples.find(a=>a.id===e.target.value);if(x)setQuery(x.query)}}><option value="">选择示例…</option>{examples.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><textarea rows={7} value={query} onChange={e=>setQuery(e.target.value)}/><div className="row"><label className="switch"><input type="checkbox" checked={useModel} onChange={e=>setUseModel(e.target.checked)}/> 调用本地 Qwen 模型</label><label className="switch"><input type="checkbox" checked={teaching} onChange={e=>setTeaching(e.target.checked)}/> 教学审核模式</label></div><div className="agent-loop"><b>本次演示的 Agent 闭环</b><span>① 模型理解任务</span><span>② 模型选择工具</span><span>③ 工具返回观察</span><span>④ 程序独立验证</span><span>⑤ 模型解释结果</span></div><details><summary>高级参数</summary><label>验证容差<input type="number" value={tol} step="1e-8" onChange={e=>setTol(+e.target.value)}/></label><label>最大重试<input type="number" min="0" max="5" value={retries} onChange={e=>setRetries(+e.target.value)}/></label></details><button className="primary" disabled={busy||query.length<3} onClick={run}>运行新任务</button>{task?.status==='waiting_review'&&<div className="review"><h3>需要人工审核</h3><p>检查当前理解、方法和参数后继续。</p><button onClick={()=>review('approve')}>批准并继续</button><button onClick={()=>review('modify')}>修改参数并继续</button><button className="danger" onClick={()=>review('reject')}>终止任务</button></div>}<div className="legend"><i className="done"/>完成 <i className="running"/>运行 <i className="review"/>审核 <i className="failed"/>失败</div></aside>
 <section className="center"><div className="panel flow"><h2>LangGraph 工作流</h2><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView onNodeClick={(_,n)=>{const ev=[...events].reverse().find(e=>e.node===n.id);setSelected(ev||null)}}><Background/><Controls/></ReactFlow></div><div className="panel detail"><h2>节点检查器</h2>{selected?<><b>{selected.title}</b><p>{selected.summary}</p><pre>{JSON.stringify(selected.payload,null,2)}</pre></>:<p className="muted">点击节点查看结构化输入、输出和耗时。</p>}</div></section>
 <section className="right"><div className="panel timeline"><h2>实时事件</h2>{events.slice().reverse().map(e=><button className={`event ${e.event_type}`} key={e.sequence} onClick={()=>setSelected(e)}><span>{e.sequence}</span><div><b>{e.title}</b><small>{e.summary}</small></div></button>)}</div>{(task?.model_calls?.length??0)>0&&<div className="panel model-calls"><h2>本地模型调用</h2>{task?.model_calls.map((m:any,i)=><div key={i}><b>{i+1}. {m.stage}</b><span>{m.provider} / {m.model}</span><small>{m.response_summary}</small><em>{m.duration_ms.toFixed(0)} ms</em></div>)}</div>}{(task?.plan?.length??0)>0&&<div className="panel"><h2>计算计划</h2>{task?.plan.map((p:any)=><p key={p.step}><b>{p.step}. {p.action}</b><br/><small>{p.tool||p.method}</small></p>)}</div>}{(task?.verification_results?.length??0)>0&&<div className="panel"><h2>程序验证</h2>{task?.verification_results.map((v:any,i)=><div className={`check ${v.passed?'pass':'fail'}`} key={i}><b>{v.passed?'✓ 通过':'✕ 未通过'} · {v.name}</b><span>{v.value.toExponential(3)} / {v.tolerance}</span></div>)}</div>}{task?.artifacts?.map((a:any,i)=><div className="panel chart" key={i}><h2>{a.title}</h2><Plot data={a.data as any} layout={{...a.layout,autosize:true,margin:{l:55,r:15,t:15,b:45},paper_bgcolor:'transparent',plot_bgcolor:'transparent'}} useResizeHandler style={{width:'100%',height:280}}/></div>)}{task?.final_answer&&<div className="panel answer"><h2>最终解释</h2><div>{renderAnswer(task.final_answer)}</div></div>}</section></section><footer>任务 ID：{task?.task_id||'尚未创建'} · 模型：{task?.model_provider||modelStatus?.provider||'检测中'} · 页面刷新后自动恢复最近任务</footer></main>
}
function renderAnswer(text:string){return text.split('\n').filter(Boolean).map((line,i)=>{const formula=line.match(/\$([^$]+)\$/);return <p key={i}>{formula?<InlineMath math={formula[1]}/>:line.replace(/\*\*/g,'').replace(/`/g,'')}</p>})}
export default App;
